Add test deploy log capture

diff --git a/.github/workflows/iac-ci-cd.yaml b/.github/workflows/iac-ci-cd.yaml
--- a/.github/workflows/iac-ci-cd.yaml
+++ b/.github/workflows/iac-ci-cd.yaml
@@ -78,7 +78,6 @@ jobs:
                     --template-file templates/networking-stack.yaml \
                     --s3-bucket atomiklabs-iac \
                     --output-template-file packaged-networking-stack.yaml
-              
 
             - name: Deploy to Test Stack
               id: deploy
@@ -100,11 +99,20 @@ jobs:
               env:
                   PARAM_FILE: ${{ needs.setup-environment.outputs.env-file }}
 
+            - name: Capture Events on Failure
+              if: failure()
+              run: |
+                  STACK_NAME="atomiklabs-test-stack-${{ github.sha }}"
+                  echo "Fetching stack events for $STACK_NAME"
+                  aws cloudformation describe-stack-events --stack-name $STACK_NAME
+                  echo "Stack events fetched."
+
             - name: Confirm Stack Creation
               run: |
                   STACK_NAME="atomiklabs-test-stack-${{ github.sha }}"
                   aws cloudformation describe-stacks --stack-name $STACK_NAME
                   echo "Stack $STACK_NAME has been confirmed to exist."
+                  
 
             - name: Delete Test Stack
               if: always()
@@ -112,6 +120,13 @@ jobs:
                   STACK_NAME="atomiklabs-test-stack-${{ github.sha }}"
                   echo "Deleting stack: $STACK_NAME"
                   aws cloudformation delete-stack --stack-name $STACK_NAME
+                  echo "Waiting for the stack to be deleted..."
+                  aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
+                  if ! aws cloudformation describe-stacks --stack-name $STACK_NAME; then
+                    echo "Stack $STACK_NAME has been deleted successfully."
+                  else
+                    echo "Stack $STACK_NAME deletion failed."
+                  fi
 
     deploy:
         if: github.event_name == 'push' && (contains(github.ref, 'refs/heads/dev') || contains(github.ref, 'refs/heads/stage') || contains(github.ref, 'refs/heads/main'))
