Add observability docker-compose folder skeleton
Add script to generate prometheus.yml dynamically from Terraform outputs

WIP infra.yaml changes for observability

Add outputs needed for interacting with observability ec2 instances

diff --git a/.github/workflows/infra.yaml b/.github/workflows/infra.yaml
--- a/.github/workflows/infra.yaml
+++ b/.github/workflows/infra.yaml
@@ -190,3 +190,101 @@ jobs:
           terraform output -json > terraform_outputs.json
           aws s3 cp terraform_outputs.json s3://${{ env.INFRA_CONFIG_BUCKET }}/${{ env.INFRA_CONFIG_PREFIX }}/${{ env.ENV_NAME }}-${{ env.OUTPUTS_PREFIX }}.json
         working-directory: ./infra/core
+
+      - name: Upload Terraform Outputs
+        uses: actions/upload-artifact@v4
+        with:
+          name: terraform_outputs
+          path: terraform_outputs.json
+
+  observability:
+    needs: core_infra
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install jq
+        run: sudo apt-get install jq
+
+      - name: Read AtomikLabs config and Set Environment Variables
+        run: |
+          config_file=".atomiklabs.json"
+          echo "AWS_REGION=$(jq -r '.infra.terraform_aws_region' "$config_file")" >> $GITHUB_ENV
+          echo "BASTION_HOST_KEY_PAIR_NAME=$(jq -r '.networking.bastion_host_key_pair_name' "$config_file")" >> $GITHUB_ENV
+          echo "INFRA_CONFIG_BUCKET=$(jq -r '.infra.infra_config_bucket' "$config_file")" >> $GITHUB_ENV
+          echo "INFRA_CONFIG_PREFIX=$(jq -r '.infra.infra_config_prefix' "$config_file")" >> $GITHUB_ENV
+          echo "OUTPUTS_PREFIX=$(jq -r '.infra.outputs_prefix' "$config_file")" >> $GITHUB_ENV
+          echo "REPO=$(jq -r '.infra.repo' "$config_file")" >> $GITHUB_ENV
+
+      - name: Load Environment Variables
+        id: load-env-vars
+        run: |
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            ENV_NAME=$(echo "${{ github.base_ref }}" | tr '/' '-')
+          else
+            ENV_NAME=$(echo "${{ github.ref_name }}" | tr '/' '-')
+          fi
+          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV
+          env_file="infra/core/environments/env.$ENV_NAME.json"
+          echo "ENV_FILE=$env_file" >> $GITHUB_ENV
+          echo "::set-output name=env_file::$env_file"
+          iam_user_name=$(jq -r '.iam_user_name' $env_file)
+          echo "IAM_USER_NAME=$iam_user_name" >> $GITHUB_ENV
+
+      - name: Set AWS Credentials Based on Environment
+        run: |
+          if [ "$ENV_NAME" == "prod" ]; then
+            echo "AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          elif [ "$ENV_NAME" == "stage" ]; then
+            echo "AWS_ACCESS_KEY_ID=${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          elif [ "$ENV_NAME" == "dev" ]; then
+            echo "AWS_ACCESS_KEY_ID=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          else
+            echo "Invalid environment name: $ENV_NAME"
+            exit 1
+          fi
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Download Terraform Outputs
+        uses: actions/download-artifact@v4
+        with:
+          name: terraform_outputs
+          path: temp
+
+      - name: Install Prometheus Config Script Dependencies
+        run: |
+          pip install -r ./infra/observability/prometheus/requirements.txt
+
+      - name: Generate Prometheus Config
+        run: |
+          python ./infra/observability/prometheus/src/generate_prometheus_config.py ./temp/terraform_outputs.json ./temp/prometheus.yml
+
+      - name: Get bastion host key pair
+        run: |
+          echo "Getting bastion host key pair"
+
+      - name: Check Docker is installed on the ec2 instance
+        run: |
+          echo "Checking if Docker is installed on the ec2 instance"
+
+      - name: Upload Prometheus Config and Docker-compose file to ec2 instance
+        run: |
+          echo "Uploading Prometheus Config to ec2 instance"
+
+      - name: Docker compose up
+        run: |
+          echo "Running docker-compose up on ec2 instance"
+
+      - name: Reload prometheus
+        run: |
+          echo "Reloading prometheus"
